In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Read data
df = pd.read_csv("Advertising.csv")
df.iloc[:5, [1, -1]]

,TV,Sales
0,230.1,22.1
1,44.5,10.4
2,17.2,9.3
3,151.5,18.5
4,180.8,12.9


In [3]:
# Calculate minimum using minimize() function
from scipy.optimize import minimize

def obj(w):
    m, b = w
    x = df.iloc[:5, 1].values
    y = df.iloc[:5, -1].values
    pred = m * x + b

    return ((pred - y) ** 2).mean()

res = minimize(obj, x0 = [0, 0])
res.x

array([0.0517618 , 8.17909235])

In [4]:
# Calculate minimum with normal equation
y = pd.DataFrame(df.iloc[:5, -1]) # Sales data (output)
y

,Sales
0,22.1
1,10.4
2,9.3
3,18.5
4,12.9


In [5]:
X = pd.DataFrame(df.iloc[:5, 1]) # TV data (input)
one = [1, 1, 1, 1, 1] # required for matrix
X["one"] = one
X

,TV,one
0,230.1,1
1,44.5,1
2,17.2,1
3,151.5,1
4,180.8,1


In [6]:
X_transpose = np.transpose(X) # TV data transposed
X_transpose

,0,1,2,3,4
TV,230.1,44.5,17.2,151.5,180.8
one,1.0,1.0,1.0,1.0,1.0


In [7]:
X_transpose_X = np.dot(X_transpose, X) # Dot product of TV data transposed x TV data
X_transpose_X

array([[1.1086299e+05, 6.2410000e+02],
       [6.2410000e+02, 5.0000000e+00]])

In [8]:
X_transpose_y = np.dot(X_transpose, y) # Dot product of TV data transposed x Sales data
X_transpose_y

array([[10843.04],
       [   73.2 ]])

In [9]:
X_transpose_X_inv = np.linalg.inv(X_transpose_X) # inverse of (TV transposed data x TV data)

In [10]:
beta = np.dot( X_transpose_X_inv, X_transpose_y ) # Normal equation
beta

array([[0.05176182],
       [8.17908951]])

In [11]:
# Output from normal equation matches output from minimize() function
print("Minimize function: ", res.x)
print("Normal equation: ", beta)

Minimize function:  [0.0517618  8.17909235]
Normal equation:  [[0.05176182]
 [8.17908951]]
